`timescale 1ns/1ps
`ifndef CPU_SEQ_V
`define CPU_SEQ_V

`include "Modules/ALU/alu.v"
`include "Modules/PC/pc.v"
`include "Modules/Reg_file/reg.v"
`include "Modules/Ins_memory/inst.v"
`include "Modules/Imm_gen/imm.v"
`include "Modules/Control/ALU_ctrl/alu_ctrl.v"
`include "Modules/Control/Main_ctrl/mcu.v"
`include "Modules/Data_memory/data_mem.v" 

module CPU_seq(
    input clk,
    input reset
);

wire ALUSrc,MemWrite,MemRead,reg_write_en;
wire [1:0] ALUOp, MemToReg;

//these wires contain some control signals which are generated by mcu and used by other modules. we can directly connect them to the respective modules without using these wires but i have declared them for better readability and understanding of the code.
wire branch,zero,jump,res_and, res_or;

wire [31:0] instr;

//These wires carry the data between different modules. For example, rs1 and rs2 are the outputs of the register file which are used as inputs to the ALU, imm_out is the output of the immediate generator which is also used as an input to the ALU, out is the output of the data memory which is used as an input to the mux for writing back to the register file, res is the output of the ALU which is used as an input to the data memory for load/store instructions and also used as an input to the mux for writing back to the register file for R-type instructions.
wire [63:0] pc_out, pc_in, rs1,rs2,imm_out,in2,alu_res,out,write_data,inc, incremented_mem_addr, branched_mem_addr; 

// res is o/p of alu,out is o/p of data mem , in2 is o/p od 1st mux , inc is i/p to adder

wire [3:0] ALU_ctrl;
pc A1(
    .clk(clk),
    .reset(reset),
    .pc_in(pc_in),
    .pc_out(pc_out)
);

instmem A2(
    .addr(pc_out),
    .instr(instr)
    );

reg_file A3(
    .clk(clk),
    .reset(reset),
    .read_reg1(instr[19:15]),
    .read_reg2(instr[24:20]),
    .write_reg(instr[11:7]),
    .write_data(write_data),
    .reg_write_en(reg_write_en),
    .read_data1(rs1),
    .read_data2(rs2)
    );

mcu A4(
    .opcode(instr[6:0]),
    .ALUSrc(ALUSrc),
    .ALUOp(ALUOp),
    .MemWrite(MemWrite),
    .MemToReg(MemToReg),
    .RegWrite(reg_write_en), 
    .branch(branch),
    .jump(jump),
    .MemRead(MemRead));

imm A5(
    .instruction(instr),
    .imm_out(imm_out)
    );

mux64 A6(
    .a(imm_out),
    .b(rs2),
    .sel(ALUSrc),
    .res(in2)
    );

ALU_Control A100(
    .ALUOp(ALUOp),
    .funct3(instr[14:12]),
    .funct7(instr[31:25]),
    .inst5(instr[5]),
    .ALU_ctrl(ALU_ctrl)
    );

alu_64_bit A7(
    .rs1(rs1),
    .rs2(in2),
    .alu_ctrl(ALU_ctrl),
    .result(alu_res),
    .zero_flag(zero),  
    .carry_flag(),
    .overflow_flag(),
    .cout()
    );

data_mem A8(
    .clk(clk),
    .reset(reset),
    .MemWrite(MemWrite),
    .MemRead(MemRead),
    .address(alu_res[9:0]),
    .write_data(rs2),
    .read_data(out)
    ); 

// mux64 A9(
//     .a(out),
//     .b(res),
//     .sel(MemToReg),
//     .res(write_data)
//     );


// Did not need this module, since we alr implemented the shift in imm.v
// barrel_shifter A10(
//     .a(imm_out),
//     .b(64'b0),         
//     .lr_flag(1'b0),
//     .logic_flag(1'b0),
//     .result(inc)
//     );

adder64 increment_by_imm(
    .a(pc_out),
    .b(imm_out),
    .adder_op(1'b0),
    .result(branched_mem_addr),
    .cout(),
    .carry_flag(),
    .overflow_flag(),
    .neg_flag()
    );
adder64 increment_by_4(
    .a(pc_out),
    .b(64'b100),
    .adder_op(1'b0),
    .result(incremented_mem_addr),
    .cout(),
    .carry_flag(),
    .overflow_flag(),
    .neg_flag()
    );
    
// writing Back
assign write_data = (MemToReg == 2'b01) ? out : (MemToReg==2'b10) ? incremented_mem_addr : alu_res; // if MemToReg = 00, write alu_res, if MemToReg = 01, write out, if MemToReg = 10, write incremented_mem_addr


assign res_and = branch & zero;
assign res_or = res_and | jump;

mux64 A14(
    .a(branched_mem_addr),
    .b(incremented_mem_addr),
    .sel(res_or),
    .res(pc_in)
    );

endmodule

`endif